# -*- coding: utf-8 -*-
"""Behavior_Based_Supplier_Segmentation_for_Procurement_Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bl1UiftFrU-m3ToRGA6uvIOFxOMJV46m

**BEHAVIOR BASED SUPPLIER SEGMENTATION FOR PROCUREMENT OPTIMIZATION**

**PHASE 1 : PROJECT SETUP**
"""

# Import Required Libraries

# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# Clustering Algorithms
from sklearn.cluster import KMeans

# Clustering Evaluation
from sklearn.metrics import silhouette_score

# Dimensionality Reduction
from sklearn.decomposition import PCA

# Ignore Warning Messages
import warnings
warnings.filterwarnings("ignore")

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Project Setup Completed Successfully")

"""**PHASE 2 : DATASET LOADING**"""

# Load Dataset into Google Colab

# Load Dataset
df = pd.read_csv("/content/1778992362206_fintech_supply_chain_03.csv")

# Display Success Message
print("Dataset Loaded Successfully")

# Display Dataset Shape
print("\nDataset Shape:")
print(df.shape)

"""**PHASE 3 : DATASET UNDERSTANDING**"""

# Basic Dataset Inspection

print("=" * 60)
print("FIRST 5 RECORDS")
print("=" * 60)

display(df.head())

print("\n")

print("=" * 60)
print("COLUMN NAMES")
print("=" * 60)

for column in df.columns:
    print(column)

print("\n")

print("=" * 60)
print("DATA TYPES")
print("=" * 60)

display(df.dtypes)

print("\n")

print("=" * 60)
print("DATASET INFORMATION")
print("=" * 60)

df.info()

"""**PHASE 4 : DATA QUALITY CHECKS**"""

# Missing Values, Duplicates and Summary Statistics

print("=" * 70)
print("MISSING VALUE ANALYSIS")
print("=" * 70)

missing_values = df.isnull().sum()

missing_report = pd.DataFrame({
    "Column": missing_values.index,
    "Missing Values": missing_values.values
})

display(missing_report)

print("\n")

print("=" * 70)
print("TOTAL MISSING VALUES IN DATASET")
print("=" * 70)

print(df.isnull().sum().sum())

print("\n")

print("=" * 70)
print("DUPLICATE RECORD ANALYSIS")
print("=" * 70)

duplicate_count = df.duplicated().sum()

print(f"Duplicate Records Found : {duplicate_count}")

print("\n")

print("=" * 70)
print("NUMERICAL COLUMN STATISTICS")
print("=" * 70)

display(df.describe())

"""**FEATURE CLASSIFICATION AND COLUMN CATEGORIZATION**"""

# Understanding Feature Types

print("=" * 70)
print("COLUMN LIST")
print("=" * 70)

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

print("\n")

print("=" * 70)
print("NUMERICAL COLUMNS")
print("=" * 70)

numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print(f"Total Numerical Columns : {len(numerical_columns)}")
print(numerical_columns)

print("\n")

print("=" * 70)
print("CATEGORICAL COLUMNS")
print("=" * 70)

categorical_columns = df.select_dtypes(
    include=["object"]
).columns.tolist()

print(f"Total Categorical Columns : {len(categorical_columns)}")
print(categorical_columns)

"""**PHASE 5 : EXPLORATORY DATA ANALYSIS**

**SECTION 1 : NUMERICAL FEATURE DISTRIBUTION ANALYSIS**
"""

# Step 1 : Define Numerical Columns

numerical_columns = [
    'buyer_count_active',
    'avg_days_invoice_to_funding',
    'invoice_first_pass_yield_pct',
    'dispute_touch_rate_12m_pct',
    'cross_border_invoice_share_pct',
    'payment_rail_mix_entropy_0_100',
    'early_settlement_discount_take_rate_pct',
    'documentary_exception_rate_12m_pct',
    'inbound_channel_digital_share_pct',
    'buyer_concentration_top3_pct'
]

# Step 2 : Create Distribution Plots

for column in numerical_columns:

    plt.figure(figsize=(8, 4))

    sns.histplot(
        data=df,
        x=column,
        kde=True
    )

    plt.title(f"Distribution of {column}")

    plt.xlabel(column)

    plt.ylabel("Frequency")

    plt.tight_layout()

    plt.show()

"""**SECTION 2 : OUTLIER ANALYSIS USING BOXPLOTS**"""

# Step 1 : Define Numerical Columns

numerical_columns = [
    'buyer_count_active',
    'avg_days_invoice_to_funding',
    'invoice_first_pass_yield_pct',
    'dispute_touch_rate_12m_pct',
    'cross_border_invoice_share_pct',
    'payment_rail_mix_entropy_0_100',
    'early_settlement_discount_take_rate_pct',
    'documentary_exception_rate_12m_pct',
    'inbound_channel_digital_share_pct',
    'buyer_concentration_top3_pct'
]

# Step 2 : Generate Boxplots


for column in numerical_columns:

    plt.figure(figsize=(8, 3))

    sns.boxplot(
        x=df[column],
        palette="viridis"
    )

    plt.title(f"Boxplot of {column}")

    plt.xlabel(column)

    plt.tight_layout()

    plt.show()

"""**SECTION 3 : CORRELATION ANALYSIS USING HEATMAP**"""

# Step 1 : Select Numerical Columns

numerical_columns = [
    'buyer_count_active',
    'avg_days_invoice_to_funding',
    'invoice_first_pass_yield_pct',
    'dispute_touch_rate_12m_pct',
    'cross_border_invoice_share_pct',
    'payment_rail_mix_entropy_0_100',
    'early_settlement_discount_take_rate_pct',
    'documentary_exception_rate_12m_pct',
    'inbound_channel_digital_share_pct',
    'buyer_concentration_top3_pct'
]

# Step 2 : Compute Correlation Matrix

correlation_matrix = df[numerical_columns].corr()

# Step 3 : Visualize Correlation Matrix

plt.figure(figsize=(12, 8))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="magma",
    fmt=".2f"
)

plt.title("Correlation Heatmap of Numerical Features")

plt.tight_layout()

plt.show()

"""**SECTION 4 : CATEGORICAL FEATURE ANALYSIS**"""

# Step 1 : Define Categorical Columns for Analysis

categorical_analysis_columns = [
    "primary_commodity_group",
    "headquarters_region",
    "annual_invoiced_usd_band",
    "sku_breadth_band",
    "peak_shipment_quarter"
]

# Step 2 : Generate Count Plots

for column in categorical_analysis_columns:

    plt.figure(figsize=(8, 5))

    sns.countplot(
        data=df,
        x=column,
        order=df[column].value_counts().index,
        palette="magma"
    )

    plt.title(f"Distribution of {column}")

    plt.xlabel(column)

    plt.ylabel("Count")

    plt.xticks(rotation=45)

    plt.tight_layout()

    plt.show()

"""**SECTION 5 : FINANCING PROGRAM PARTICIPATION ANALYSIS**"""

# Step 1 : Define Financing Program Columns

financing_program_columns = [
    "program_reverse_factoring_active",
    "program_dynamic_discount_enrolled",
    "program_inventory_finance_active",
    "program_virtual_card_settlement",
    "program_logistics_pay_active"
]

# Step 2 : Create Count Plots for Each Program

for column in financing_program_columns:

    plt.figure(figsize=(6, 4))

    sns.countplot(
        data=df,
        x=column,
        palette="viridis"
    )

    plt.title(f"Participation in {column}")

    plt.xlabel("Status")

    plt.ylabel("Number of Suppliers")

    plt.tight_layout()

    plt.show()

"""**PHASE 6 : FEATURE PREPROCESSING**"""

# Convert Raw Dataset into ML Ready Dataset
# Step 1 : Create Working Copy

df_processed = df.copy()

print("Working copy created successfully.")

# Step 2 : Store Supplier IDs Separately
# Supplier IDs will be used later for reporting

supplier_ids = df_processed["supplier_id"]

print("Supplier IDs stored separately.")

# Step 3 : Remove Non-ML Columns

columns_to_drop = [
    "supplier_id",
    "snapshot_quarter"
]

df_processed.drop(
    columns=columns_to_drop,
    inplace=True
)

print("Non-ML columns removed.")

# Step 4 : Ordinal Encoding
# annual_invoiced_usd_band

invoice_band_mapping = {
    "Under 2M": 1,
    "2M–10M": 2,
    "10M–50M": 3,
    "50M+": 4
}

df_processed["annual_invoiced_usd_band"] = (
    df_processed["annual_invoiced_usd_band"]
    .map(invoice_band_mapping)
)

print("annual_invoiced_usd_band encoded.")

# Step 5 : Ordinal Encoding
# sku_breadth_band

sku_band_mapping = {
    "Narrow": 1,
    "Medium": 2,
    "Broad": 3,
    "Very broad": 4
}

df_processed["sku_breadth_band"] = (
    df_processed["sku_breadth_band"]
    .map(sku_band_mapping)
)

print("sku_breadth_band encoded.")

# Step 6 : Binary Encoding
# Financing Program Columns

binary_columns = [
    "program_reverse_factoring_active",
    "program_dynamic_discount_enrolled",
    "program_inventory_finance_active",
    "program_virtual_card_settlement",
    "program_logistics_pay_active"
]

for column in binary_columns:

    df_processed[column] = df_processed[column].map({
        "Yes": 1,
        "No": 0
    })

print("Binary encoding completed.")

# Step 7 : One-Hot Encoding

one_hot_columns = [
    "primary_commodity_group",
    "headquarters_region",
    "peak_shipment_quarter"
]

df_processed = pd.get_dummies(
    df_processed,
    columns=one_hot_columns,
    drop_first=True
)

print("One-Hot Encoding completed.")

# Step 8 : Display Final Dataset Information

print("\nProcessed Dataset Shape:")
print(df_processed.shape)

print("\nFirst Five Records:")
display(df_processed.head())

"""**PHASE 7 : FEATURE SCALING**"""

# Standardize Features Before Clustering
# Step 1 : Initialize Standard Scaler

scaler = StandardScaler()

print("StandardScaler initialized successfully.")

# Step 2 : Scale All Features

scaled_features = scaler.fit_transform(df_processed)

print("Feature scaling completed successfully.")

# Step 3 : Convert Scaled Data Back to DataFrame

df_scaled = pd.DataFrame(
    scaled_features,
    columns=df_processed.columns
)
print("Scaled DataFrame created successfully.")

# Step 4 : Display Information

print("\nScaled Dataset Shape:")
print(df_scaled.shape)

print("\nFirst Five Records of Scaled Dataset:")
display(df_scaled.head())

"""**PHASE 8 : CLUSTER ANALYSIS**

**SECTION 1 : ELBOW METHOD**
"""

# SECTION 1 : ELBOW METHOD
# Determine Optimal Number of Clusters
# Step 1 : Create Empty List to Store WCSS Values

wcss = []

# Step 2 : Train K-Means for Different K Values

for k in range(1, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(df_scaled)

    wcss.append(kmeans.inertia_)

# Step 3 : Plot Elbow Curve

plt.figure(figsize=(10, 5))

plt.plot(
    range(1, 11),
    wcss,
    marker="o"
)

plt.title("Elbow Method for Optimal Number of Clusters")

plt.xlabel("Number of Clusters (K)")

plt.ylabel("WCSS")

plt.grid(True)

plt.show()

"""**SECTION 2 : SILHOUETTE ANALYSIS**"""

# SECTION 2 : SILHOUETTE ANALYSIS
# Determine Best Cluster Count Using Silhouette Score
# Step 1 : Create Empty List
silhouette_scores = []

# Step 2 : Calculate Silhouette Score

for k in range(2, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    cluster_labels = kmeans.fit_predict(df_scaled)

    score = silhouette_score(
        df_scaled,
        cluster_labels
    )

    silhouette_scores.append(score)

# Step 3 : Create Results DataFrame

silhouette_results = pd.DataFrame({
    "K": range(2, 11),
    "Silhouette Score": silhouette_scores
})

# Step 4 : Display Scores

display(silhouette_results)

# Step 5 : Plot Scores

plt.figure(figsize=(10, 5))

plt.plot(
    range(2, 11),
    silhouette_scores,
    marker="o"
)

plt.title("Silhouette Analysis")

plt.xlabel("Number of Clusters (K)")

plt.ylabel("Silhouette Score")

plt.grid(True)

plt.show()

"""**PHASE 9 : K-MEANS MODEL TRAINING**"""

# Train Final K-Means Model Using K = 4
# Step 1 : Initialize K-Means Model

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

print("K-Means model initialized successfully.")


# Step 2 : Train Model and Generate Cluster Labels

cluster_labels = kmeans.fit_predict(df_scaled)

print("Cluster labels generated successfully.")


# Step 3 : Add Cluster Labels to Processed Dataset

df_processed["Cluster"] = cluster_labels

print("Cluster column added successfully.")


# Step 4 : Create Final Segmentation Dataset

supplier_segmentation = df_processed.copy()

supplier_segmentation.insert(
    0,
    "supplier_id",
    supplier_ids
)

print("Supplier IDs added back successfully.")


# Step 5 : Display Cluster Distribution

print("\nCluster Distribution:")

display(
    supplier_segmentation["Cluster"]
    .value_counts()
    .sort_index()
)


# Step 6 : Preview Segmented Suppliers

print("\nFirst Five Segmented Suppliers:")

display(
    supplier_segmentation[
        ["supplier_id", "Cluster"]
    ].head()
)

"""**PHASE 10 : CLUSTER EVALUATION**"""

# Evaluate Final K-Means Clustering Model
# Step 1 : Calculate Final Silhouette Score

final_silhouette_score = silhouette_score(
    df_scaled,
    cluster_labels
)


# Step 2 : Display Evaluation Metrics
print("=" * 60)
print("CLUSTER EVALUATION RESULTS")
print("=" * 60)
print(f"\nNumber of Clusters : {kmeans.n_clusters}")

print(f"\nFinal Silhouette Score : {final_silhouette_score:.4f}")


# Step 3 : Display Cluster Distribution

print("\nCluster Distribution:")

cluster_distribution = (
    supplier_segmentation["Cluster"]
    .value_counts()
    .sort_index()
)

display(cluster_distribution)


# Step 4 : Cluster Percentage Distribution

cluster_percentage = (
    supplier_segmentation["Cluster"]
    .value_counts(normalize=True)
    .sort_index() * 100
)

print("\nCluster Percentage Distribution:")

display(cluster_percentage.round(2))

"""**PHASE 11 : PCA VISUALIZATION**"""

# Visualize Supplier Segments in 2 Dimensions
# Step 1 : Initialize PCA
pca = PCA(
    n_components=2,
    random_state=42
)


# Step 2 : Transform Scaled Dataset

pca_components = pca.fit_transform(df_scaled)

# Step 3 : Create PCA DataFrame

pca_df = pd.DataFrame(
    pca_components,
    columns=[
        "Principal_Component_1",
        "Principal_Component_2"
    ]
)


# Step 4 : Add Cluster Labels

pca_df["Cluster"] = cluster_labels


# Step 5 : Create Scatter Plot

plt.figure(figsize=(12, 8))

sns.scatterplot(
    data=pca_df,
    x="Principal_Component_1",
    y="Principal_Component_2",
    hue="Cluster",
    palette="magma",
    alpha=0.7
)

plt.title("Supplier Segments Visualized Using PCA")

plt.xlabel("Principal Component 1")

plt.ylabel("Principal Component 2")

plt.legend(title="Cluster")

plt.tight_layout()

plt.show()

"""**PHASE 12 : CLUSTER PROFILING**"""

# Understand Characteristics of Each Supplier Segment
# Step 1 : Calculate Cluster-wise Mean Values

cluster_profile = (
    supplier_segmentation
    .groupby("Cluster")
    .mean(numeric_only=True)
)


# Step 2 : Display Cluster Profiles

print("Cluster Profile Summary")
display(cluster_profile.round(2))

"""**CLUSTER INTERPRETATION AND SEGMENT NAMING**"""

# Step 1 : Calculate Segment Counts

segment_counts = (
    supplier_segmentation["Cluster"]
    .value_counts()
    .sort_index()
)

segment_percentages = (
    supplier_segmentation["Cluster"]
    .value_counts(normalize=True)
    .sort_index() * 100
)


# Step 2 : Create Interpretation Table

cluster_interpretation = pd.DataFrame({

    "Cluster": [0, 1, 2, 3],

    "Segment Name": [
        "Cross-Border High-Risk Suppliers",
        "Operationally Efficient Suppliers",
        "Strategic Large-Value Suppliers",
        "Broad-Network Operational Suppliers"
    ],

    "Supplier Count": segment_counts.values,

    "Percentage (%)": segment_percentages.round(2).values,

    "Key Dataset Features Used For Naming": [

        "High cross_border_invoice_share_pct, high dispute_touch_rate_12m_pct, high documentary_exception_rate_12m_pct, low invoice_first_pass_yield_pct",

        "Low avg_days_invoice_to_funding, high invoice_first_pass_yield_pct, low dispute_touch_rate_12m_pct, high inbound_channel_digital_share_pct",

        "High annual_invoiced_usd_band, high buyer_concentration_top3_pct, high invoice_first_pass_yield_pct",

        "High buyer_count_active, high sku_breadth_band, low buyer_concentration_top3_pct"
    ]
})

display(cluster_interpretation)

"""**SUPPLIER SEGMENT MAPPING TO SUPPLIER_ID**"""

# Map Every Supplier To A Business Segment
# Step 1 : Add Segment Names To Dataset

segment_names = {
    0: "Cross-Border High-Risk Suppliers",
    1: "Operationally Efficient Suppliers",
    2: "Strategic Large-Value Suppliers",
    3: "Broad-Network Operational Suppliers"
}

supplier_segmentation["Segment_Name"] = (
    supplier_segmentation["Cluster"]
    .map(segment_names)
)


# Step 2 : Display Sample Supplier Assignments

print("Sample Supplier Segment Assignments")

display(
    supplier_segmentation[
        ["supplier_id", "Cluster", "Segment_Name"]
    ].head(20)
)


# Step 3 : Display Supplier Count Per Segment

print("\nSupplier Count Per Segment")

display(
    supplier_segmentation["Segment_Name"]
    .value_counts()
)

"""**SUPPLIER LOOKUP UTILITY**"""

# Find Which Segment A Supplier Belongs To
# Step 1 : Enter Supplier ID
supplier_id_to_search = "FTSC3-00000003"


# Step 2 : Search Supplier
result = supplier_segmentation[
    supplier_segmentation["supplier_id"]
    == supplier_id_to_search
]

# Step 3 : Display Result
if len(result) > 0:

    print("Supplier Segment Details")

    display(
        result[
            ["supplier_id", "Cluster", "Segment_Name"]
        ]
    )

else:

    print("Supplier ID not found.")

"""**PHASE 13 : FINAL OUTPUT**

**SUPPLIER BEHAVIOUR SEGMENT VISUALIZATION**
"""

# Step 1 : Select Key Behaviour Metrics
behaviour_summary = (
    supplier_segmentation
    .groupby("Cluster")
    [
        [
            "avg_days_invoice_to_funding",
            "invoice_first_pass_yield_pct",
            "dispute_touch_rate_12m_pct",
            "cross_border_invoice_share_pct"
        ]
    ]
    .mean()
)

# Step 2 : Rename Clusters For Readability

behaviour_summary.index = [

    "Cross-Border High-Risk",

    "Operationally Efficient",

    "Strategic Large-Value",

    "Broad-Network Operational"
]

# Step 3 : Rename Columns Based On Problem Statement

behaviour_summary.columns = [

    "Timing",

    "Invoice Quality",

    "Dispute Cadence",

    "Corridor Mix"
]


# Step 4 : Create Heatmap

plt.figure(figsize=(12, 6))

sns.heatmap(
    behaviour_summary,
    annot=True,
    fmt=".2f",
    cmap="YlGnBu",
    linewidths=0.5
)

plt.title(
    "Supplier Behaviour Segments Based on Timing, Invoice Quality, Dispute Cadence and Corridor Mix",
    fontsize=14
)

plt.xlabel("Behaviour Dimensions")

plt.ylabel("Supplier Segments")

plt.tight_layout()

plt.show()

"""**FINAL SUPPLIER SEGMENTATION SUMMARY**"""

# Step 1 : Create Final Output Table

final_output = pd.DataFrame({

    "Supplier Segment": [

        "Cross-Border High-Risk Suppliers",

        "Operationally Efficient Suppliers",

        "Strategic Large-Value Suppliers",

        "Broad-Network Operational Suppliers"
    ],

    "Timing Behaviour": [

        "Slowest Funding Cycle",

        "Fastest Funding Cycle",

        "Moderate Funding Cycle",

        "Moderate Funding Cycle"
    ],

    "Invoice Quality": [

        "Lowest Invoice Quality",

        "Highest Invoice Quality",

        "High Invoice Quality",

        "Good Invoice Quality"
    ],

    "Dispute Cadence": [

        "Highest Dispute Rate",

        "Lowest Dispute Rate",

        "Low Dispute Rate",

        "Moderate Dispute Rate"
    ],

    "Corridor Mix": [

        "Highest Cross-Border Activity",

        "Lower Cross-Border Activity",

        "Moderate Cross-Border Activity",

        "Lowest Cross-Border Activity"
    ],

    "Playbook": [

        "Compliance Monitoring & Exception Management",

        "Preferred Supplier Program & Financing Expansion",

        "Strategic Supplier Relationship Management",

        "Operational Efficiency & Process Optimization"
    ],

    "Limits Strategy": [

        "Conservative Financing Limits",

        "Expanded Financing Limits",

        "Risk-Adjusted Financing Limits",

        "Standard Financing Limits"
    ],

    "Education Strategy": [

        "Documentation Quality & Dispute Prevention",

        "Advanced Digital Adoption Programs",

        "Strategic Risk Awareness Programs",

        "Process Automation & Digital Workflow Training"
    ]
})


# Step 2 : Display Styled Final Output

display(

    final_output.style

    .set_caption(
        "Final Supplier Segmentation Output for Procurement Optimization"
    )

    .set_properties(**{
        "text-align": "left",
        "white-space": "normal"
    })

    .set_table_styles([
        {
            "selector": "caption",
            "props": [
                ("font-size", "18px"),
                ("font-weight", "bold"),
                ("text-align", "center")
            ]
        },
        {
            "selector": "th",
            "props": [
                ("font-size", "12px"),
                ("font-weight", "bold"),
                ("text-align", "center")
            ]
        }
    ])

    .hide(axis="index")

)

"""**PHASE 14 : FINAL CONCLUSION**"""

from IPython.display import display, HTML

display(HTML("""

<div style="
    background-color:#f8f9fa;
    padding:20px;
    border-radius:10px;
    border-left:6px solid #6f42c1;
    font-family:Arial;
">

<h3 style="color:#6f42c1;">
Final Conclusion
</h3>

<p style="font-size:15px; line-height:1.8;">

The supplier segmentation analysis successfully identified
<b>four distinct supplier behaviour segments</b> based on
<b>Timing Behaviour, Invoice Quality, Dispute Cadence, and Corridor Mix</b>.

<br><br>

The analysis revealed that
<b>Operationally Efficient Suppliers</b> and
<b>Strategic Large-Value Suppliers</b>
exhibited the most similar behaviour patterns, characterized by
high invoice quality, low dispute rates, and efficient funding cycles.

<br><br>

<b>Cross-Border High-Risk Suppliers</b>
emerged as the most distinct segment due to slower funding cycles,
lower invoice quality, higher dispute rates, and greater cross-border activity,
while <b>Broad-Network Operational Suppliers</b> demonstrated balanced operational behaviour with diversified buyer relationships and moderate performance across all key dimensions.

<br><br>

These behaviour-based segments provide procurement leadership with a
<b>data-driven view of supplier performance</b>, enabling targeted playbooks,
financing limits, monitoring strategies, and supplier education programs to proactively
reduce operational exceptions before they escalate.

</p>

</div>

"""))